### ISSUE TITLE
circup pulls down ulab version regardless

### ISSUE THREAD

**Issue by clohl** [CedarGroveStudios/CircuitPython_PaletteFader#2]
Tried to install via circup but ever since Adafruit removed the ulab module from matrixportal M4 it's not working.  Looks like no matter what it pulls down the ulab version currently.  I've reverted to copy pasta for now.

I'm importing correctly (to avoid ulab):

```
from cedargrove_palettefader.palettefader import PaletteFader
...
reshade = PaletteFader(source_palette=color, brightness=0.5)
color = reshade.palette
------------------------------------------
Traceback (most recent call last):
  File "code.py", line 16, in <module>
  File "cedargrove_palettefader.py", line 41, in <module>
ImportError: no module named 'ulab'```

**Comment by CedarGroveStudios** [comment]
That’s interesting. Circup should be refreshing the  cedargrove_palettefader folder with both versions. Perhaps the previous cedargrove_palettefader.mpy that’s in the device’s lib folder — the version without the folder of the two versions — needs to be manually deleted from the lib folder first. I’ll look into it later tonight. Glad you were able to get it working for you. Thanks for the feedback.

**Comment by CedarGroveStudios** [comment]
It appears that the Community Bundle is linked to the old version. The PaletteFader release was re-released a few minutes ago to see if that makes the needed change. The update should automatically happen when the workflow runs at 1:30AM US Eastern tonight. Thanks again for catching this.

**Comment by CedarGroveStudios** [comment]
Refreshing the release made the non-ulab code available but exposed a version numbering scheme error. Tonight’s bundle workflow should fix the remaining issue.

**Comment by CedarGroveStudios** [comment]
After tonight's Community Bundle workflow, it's working with `circup` as it should. I'll close the issue now. Appreciate your help with this, @clohl.
